"""
Utils Module
Utilidades y helpers de la aplicación
"""

from .audit_logger import AuditEventType, AuditLogger, audit_logger, get_audit_logger
from .backup_manager import BackupManager, backup_manager, get_backup_manager
from .document_manager import DocumentManager, document_manager
from .helpers import (
    calculate_age,
    clean_string,
    ensure_directory_exists,
    format_currency,
    format_date,
    format_file_size,
    format_phone_number,
    generate_unique_filename,
    get_file_extension,
    get_resource_path,
    get_timestamp,
    is_valid_image_file,
    is_valid_pdf_file,
    log_message,
    mantener_ventana_al_frente,
    normalize_string,
    parse_currency,
    parse_date,
    quitar_ventana_al_frente,
    safe_divide,
    truncate_text,
    validate_cedula,
    validate_email,
)
from .pdf_generator import PDFGenerator, pdf_generator
from .security import (
    PermissionChecker,
    SecurityLogger,
    SecurityValidator,
    permission_checker,
    security_logger,
    security_validator,
)
from .validators import (
    DocumentoValidator,
    EmpleadoValidator,
    IncidenciaValidator,
    PagoValidator,
    ValidationError,
    Validator,
)

__all__ = [
    "get_resource_path",
    "format_date",
    "parse_date",
    "format_currency",
    "parse_currency",
    "format_phone_number",
    "validate_cedula",
    "validate_email",
    "calculate_age",
    "truncate_text",
    "normalize_string",
    "get_file_extension",
    "is_valid_image_file",
    "is_valid_pdf_file",
    "format_file_size",
    "safe_divide",
    "clean_string",
    "generate_unique_filename",
    "ensure_directory_exists",
    "get_timestamp",
    "log_message",
    "mantener_ventana_al_frente",
    "quitar_ventana_al_frente",
    "ValidationError",
    "Validator",
    "EmpleadoValidator",
    "DocumentoValidator",
    "IncidenciaValidator",
    "PagoValidator",
    "DocumentManager",
    "document_manager",
    "PDFGenerator",
    "pdf_generator",
    "BackupManager",
    "backup_manager",
    "get_backup_manager",
    "AuditLogger",
    "audit_logger",
    "get_audit_logger",
    "AuditEventType",
    "SecurityValidator",
    "PermissionChecker",
    "SecurityLogger",
    "security_validator",
    "permission_checker",
    "security_logger",
]
